export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const GET_USER = 'GET_USER';
export const GET_VACCINES = 'GET_VACCINES';
export const GET_VACCINE_CALENDAR = 'GET_VACCINE_CALENDAR';
export const GET_INJECTED_LOCATIONS = 'GET_INJECTED_LOCATIONS';
export const POST_VACCINE_CALENDAR = 'POST_VACCINE_CALENDAR';